### PR TITLE
Better error handling in FBS (off-line)

### PR DESCRIPTION
**Pull request by cableman**
* Index error when logging message from FBS that is an error
* Ensure that network errors results in "FBS Offline" error and logging of the error is not empty

### CODE REVIEW

**Comment by cableman** [comment]
Fixed JS style errors. The last errors are not fixed as the file is kept in old codestyle to match the old bibbox. It's the same file in both projects.

**Review by turegjorup — COMMENTED** [review]
Not sure if `L119` `var err = null;` should be renamed to `error` as well? Same thing in `L141`. Is it deliberate that you havn't renamed all `err`  to `error`? If so, possibly rename one or both for better readability.

**Review by turegjorup — COMMENTED** [review]
Also, I respect that you are want to keep the files identical between both apps. But please use https://standardjs.com/#how-do-i-disable-a-rule or similar with appropriate comment as explanation.

**Comment by cableman** [comment]
It's an project thing, so I don't want to start using this now... also it's part of the when should the old system be dropped etc.

**Review by turegjorup — APPROVED** [review]
Approved with comments. See above.

**Comment by cableman** [comment]
To the err thing yes, it's two different errors the `error` is the error from request (http error) while the err in the else is if the service returns an err in the XML that was parsed. So they are not related.

**Comment by turegjorup** [comment]
> To the err thing yes, it's two different errors the `error` is the error from request (http error) while the err in the else is if the service returns an err in the XML that was parsed. So they are not related.

Then `httpError` and `xmlError` seems like better names?

**Pull request merged**
